"""autogenerated by genpy from k2_client/Expressions.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Expressions(genpy.Message):
  _md5sum = "5cb5b766a73d02643dd57183072cb85d"
  _type = "k2_client/Expressions"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool neutral
bool happy
"""
  __slots__ = ['neutral','happy']
  _slot_types = ['bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       neutral,happy

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Expressions, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.neutral is None:
        self.neutral = False
      if self.happy is None:
        self.happy = False
    else:
      self.neutral = False
      self.happy = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2B.pack(_x.neutral, _x.happy))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.neutral, _x.happy,) = _struct_2B.unpack(str[start:end])
      self.neutral = bool(self.neutral)
      self.happy = bool(self.happy)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2B.pack(_x.neutral, _x.happy))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.neutral, _x.happy,) = _struct_2B.unpack(str[start:end])
      self.neutral = bool(self.neutral)
      self.happy = bool(self.happy)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2B = struct.Struct("<2B")
