"""autogenerated by genpy from k2_client/JointPositionAndState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class JointPositionAndState(genpy.Message):
  _md5sum = "fffd6acd4cf38509c6d9ae24639d6b49"
  _type = "k2_client/JointPositionAndState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool trackingState
geometry_msgs/Point position
int32 jointType
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

"""
  __slots__ = ['trackingState','position','jointType']
  _slot_types = ['bool','geometry_msgs/Point','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       trackingState,position,jointType

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(JointPositionAndState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.trackingState is None:
        self.trackingState = False
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.jointType is None:
        self.jointType = 0
    else:
      self.trackingState = False
      self.position = geometry_msgs.msg.Point()
      self.jointType = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B3di.pack(_x.trackingState, _x.position.x, _x.position.y, _x.position.z, _x.jointType))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 29
      (_x.trackingState, _x.position.x, _x.position.y, _x.position.z, _x.jointType,) = _struct_B3di.unpack(str[start:end])
      self.trackingState = bool(self.trackingState)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B3di.pack(_x.trackingState, _x.position.x, _x.position.y, _x.position.z, _x.jointType))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 29
      (_x.trackingState, _x.position.x, _x.position.y, _x.position.z, _x.jointType,) = _struct_B3di.unpack(str[start:end])
      self.trackingState = bool(self.trackingState)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B3di = struct.Struct("<B3di")
