"""autogenerated by genpy from k2_client/Body.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import k2_client.msg
import geometry_msgs.msg
import std_msgs.msg

class Body(genpy.Message):
  _md5sum = "f2413f69b470a1bf6ed2eb6a8b85abf2"
  _type = "k2_client/Body"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
int32 leanTrackingState
Lean lean
bool isRestricted
bool isTracked
uint64 trackingId
int32 clippedEdges
bool engaged
float32 handRightConfidence
int32 handRightState
float32 handLeftConfidence
int32 handLeftState
Appearance appearance
Activities activities
Expressions expressions
JointOrientationAndType[] jointOrientations
JointPositionAndState[] jointPositions
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: k2_client/Lean
float64 leanX
float64 leanY
================================================================================
MSG: k2_client/Appearance
bool wearingGlasses
================================================================================
MSG: k2_client/Activities
bool eyeLeftClosed
bool eyeRightClosed
bool mouthOpen
bool mouthMoved
bool lookingAway
================================================================================
MSG: k2_client/Expressions
bool neutral
bool happy
================================================================================
MSG: k2_client/JointOrientationAndType
geometry_msgs/Quaternion orientation
int32 jointType
================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: k2_client/JointPositionAndState
bool trackingState
geometry_msgs/Point position
int32 jointType
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

"""
  __slots__ = ['header','leanTrackingState','lean','isRestricted','isTracked','trackingId','clippedEdges','engaged','handRightConfidence','handRightState','handLeftConfidence','handLeftState','appearance','activities','expressions','jointOrientations','jointPositions']
  _slot_types = ['std_msgs/Header','int32','k2_client/Lean','bool','bool','uint64','int32','bool','float32','int32','float32','int32','k2_client/Appearance','k2_client/Activities','k2_client/Expressions','k2_client/JointOrientationAndType[]','k2_client/JointPositionAndState[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,leanTrackingState,lean,isRestricted,isTracked,trackingId,clippedEdges,engaged,handRightConfidence,handRightState,handLeftConfidence,handLeftState,appearance,activities,expressions,jointOrientations,jointPositions

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Body, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.leanTrackingState is None:
        self.leanTrackingState = 0
      if self.lean is None:
        self.lean = k2_client.msg.Lean()
      if self.isRestricted is None:
        self.isRestricted = False
      if self.isTracked is None:
        self.isTracked = False
      if self.trackingId is None:
        self.trackingId = 0
      if self.clippedEdges is None:
        self.clippedEdges = 0
      if self.engaged is None:
        self.engaged = False
      if self.handRightConfidence is None:
        self.handRightConfidence = 0.
      if self.handRightState is None:
        self.handRightState = 0
      if self.handLeftConfidence is None:
        self.handLeftConfidence = 0.
      if self.handLeftState is None:
        self.handLeftState = 0
      if self.appearance is None:
        self.appearance = k2_client.msg.Appearance()
      if self.activities is None:
        self.activities = k2_client.msg.Activities()
      if self.expressions is None:
        self.expressions = k2_client.msg.Expressions()
      if self.jointOrientations is None:
        self.jointOrientations = []
      if self.jointPositions is None:
        self.jointPositions = []
    else:
      self.header = std_msgs.msg.Header()
      self.leanTrackingState = 0
      self.lean = k2_client.msg.Lean()
      self.isRestricted = False
      self.isTracked = False
      self.trackingId = 0
      self.clippedEdges = 0
      self.engaged = False
      self.handRightConfidence = 0.
      self.handRightState = 0
      self.handLeftConfidence = 0.
      self.handLeftState = 0
      self.appearance = k2_client.msg.Appearance()
      self.activities = k2_client.msg.Activities()
      self.expressions = k2_client.msg.Expressions()
      self.jointOrientations = []
      self.jointPositions = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_i2d2BQiBfifi8B.pack(_x.leanTrackingState, _x.lean.leanX, _x.lean.leanY, _x.isRestricted, _x.isTracked, _x.trackingId, _x.clippedEdges, _x.engaged, _x.handRightConfidence, _x.handRightState, _x.handLeftConfidence, _x.handLeftState, _x.appearance.wearingGlasses, _x.activities.eyeLeftClosed, _x.activities.eyeRightClosed, _x.activities.mouthOpen, _x.activities.mouthMoved, _x.activities.lookingAway, _x.expressions.neutral, _x.expressions.happy))
      length = len(self.jointOrientations)
      buff.write(_struct_I.pack(length))
      for val1 in self.jointOrientations:
        _v1 = val1.orientation
        _x = _v1
        buff.write(_struct_4d.pack(_x.x, _x.y, _x.z, _x.w))
        buff.write(_struct_i.pack(val1.jointType))
      length = len(self.jointPositions)
      buff.write(_struct_I.pack(length))
      for val1 in self.jointPositions:
        buff.write(_struct_B.pack(val1.trackingState))
        _v2 = val1.position
        _x = _v2
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        buff.write(_struct_i.pack(val1.jointType))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lean is None:
        self.lean = k2_client.msg.Lean()
      if self.appearance is None:
        self.appearance = k2_client.msg.Appearance()
      if self.activities is None:
        self.activities = k2_client.msg.Activities()
      if self.expressions is None:
        self.expressions = k2_client.msg.Expressions()
      if self.jointOrientations is None:
        self.jointOrientations = None
      if self.jointPositions is None:
        self.jointPositions = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 59
      (_x.leanTrackingState, _x.lean.leanX, _x.lean.leanY, _x.isRestricted, _x.isTracked, _x.trackingId, _x.clippedEdges, _x.engaged, _x.handRightConfidence, _x.handRightState, _x.handLeftConfidence, _x.handLeftState, _x.appearance.wearingGlasses, _x.activities.eyeLeftClosed, _x.activities.eyeRightClosed, _x.activities.mouthOpen, _x.activities.mouthMoved, _x.activities.lookingAway, _x.expressions.neutral, _x.expressions.happy,) = _struct_i2d2BQiBfifi8B.unpack(str[start:end])
      self.isRestricted = bool(self.isRestricted)
      self.isTracked = bool(self.isTracked)
      self.engaged = bool(self.engaged)
      self.appearance.wearingGlasses = bool(self.appearance.wearingGlasses)
      self.activities.eyeLeftClosed = bool(self.activities.eyeLeftClosed)
      self.activities.eyeRightClosed = bool(self.activities.eyeRightClosed)
      self.activities.mouthOpen = bool(self.activities.mouthOpen)
      self.activities.mouthMoved = bool(self.activities.mouthMoved)
      self.activities.lookingAway = bool(self.activities.lookingAway)
      self.expressions.neutral = bool(self.expressions.neutral)
      self.expressions.happy = bool(self.expressions.happy)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.jointOrientations = []
      for i in range(0, length):
        val1 = k2_client.msg.JointOrientationAndType()
        _v3 = val1.orientation
        _x = _v3
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _struct_4d.unpack(str[start:end])
        start = end
        end += 4
        (val1.jointType,) = _struct_i.unpack(str[start:end])
        self.jointOrientations.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.jointPositions = []
      for i in range(0, length):
        val1 = k2_client.msg.JointPositionAndState()
        start = end
        end += 1
        (val1.trackingState,) = _struct_B.unpack(str[start:end])
        val1.trackingState = bool(val1.trackingState)
        _v4 = val1.position
        _x = _v4
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        start = end
        end += 4
        (val1.jointType,) = _struct_i.unpack(str[start:end])
        self.jointPositions.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_i2d2BQiBfifi8B.pack(_x.leanTrackingState, _x.lean.leanX, _x.lean.leanY, _x.isRestricted, _x.isTracked, _x.trackingId, _x.clippedEdges, _x.engaged, _x.handRightConfidence, _x.handRightState, _x.handLeftConfidence, _x.handLeftState, _x.appearance.wearingGlasses, _x.activities.eyeLeftClosed, _x.activities.eyeRightClosed, _x.activities.mouthOpen, _x.activities.mouthMoved, _x.activities.lookingAway, _x.expressions.neutral, _x.expressions.happy))
      length = len(self.jointOrientations)
      buff.write(_struct_I.pack(length))
      for val1 in self.jointOrientations:
        _v5 = val1.orientation
        _x = _v5
        buff.write(_struct_4d.pack(_x.x, _x.y, _x.z, _x.w))
        buff.write(_struct_i.pack(val1.jointType))
      length = len(self.jointPositions)
      buff.write(_struct_I.pack(length))
      for val1 in self.jointPositions:
        buff.write(_struct_B.pack(val1.trackingState))
        _v6 = val1.position
        _x = _v6
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        buff.write(_struct_i.pack(val1.jointType))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lean is None:
        self.lean = k2_client.msg.Lean()
      if self.appearance is None:
        self.appearance = k2_client.msg.Appearance()
      if self.activities is None:
        self.activities = k2_client.msg.Activities()
      if self.expressions is None:
        self.expressions = k2_client.msg.Expressions()
      if self.jointOrientations is None:
        self.jointOrientations = None
      if self.jointPositions is None:
        self.jointPositions = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 59
      (_x.leanTrackingState, _x.lean.leanX, _x.lean.leanY, _x.isRestricted, _x.isTracked, _x.trackingId, _x.clippedEdges, _x.engaged, _x.handRightConfidence, _x.handRightState, _x.handLeftConfidence, _x.handLeftState, _x.appearance.wearingGlasses, _x.activities.eyeLeftClosed, _x.activities.eyeRightClosed, _x.activities.mouthOpen, _x.activities.mouthMoved, _x.activities.lookingAway, _x.expressions.neutral, _x.expressions.happy,) = _struct_i2d2BQiBfifi8B.unpack(str[start:end])
      self.isRestricted = bool(self.isRestricted)
      self.isTracked = bool(self.isTracked)
      self.engaged = bool(self.engaged)
      self.appearance.wearingGlasses = bool(self.appearance.wearingGlasses)
      self.activities.eyeLeftClosed = bool(self.activities.eyeLeftClosed)
      self.activities.eyeRightClosed = bool(self.activities.eyeRightClosed)
      self.activities.mouthOpen = bool(self.activities.mouthOpen)
      self.activities.mouthMoved = bool(self.activities.mouthMoved)
      self.activities.lookingAway = bool(self.activities.lookingAway)
      self.expressions.neutral = bool(self.expressions.neutral)
      self.expressions.happy = bool(self.expressions.happy)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.jointOrientations = []
      for i in range(0, length):
        val1 = k2_client.msg.JointOrientationAndType()
        _v7 = val1.orientation
        _x = _v7
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _struct_4d.unpack(str[start:end])
        start = end
        end += 4
        (val1.jointType,) = _struct_i.unpack(str[start:end])
        self.jointOrientations.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.jointPositions = []
      for i in range(0, length):
        val1 = k2_client.msg.JointPositionAndState()
        start = end
        end += 1
        (val1.trackingState,) = _struct_B.unpack(str[start:end])
        val1.trackingState = bool(val1.trackingState)
        _v8 = val1.position
        _x = _v8
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        start = end
        end += 4
        (val1.jointType,) = _struct_i.unpack(str[start:end])
        self.jointPositions.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
_struct_i2d2BQiBfifi8B = struct.Struct("<i2d2BQiBfifi8B")
_struct_i = struct.Struct("<i")
_struct_3I = struct.Struct("<3I")
_struct_4d = struct.Struct("<4d")
_struct_3d = struct.Struct("<3d")
