/* Auto-generated by genmsg_cpp for file /home/prdemo/ros/local/k2_client/msg/Activities.msg */
#ifndef K2_CLIENT_MESSAGE_ACTIVITIES_H
#define K2_CLIENT_MESSAGE_ACTIVITIES_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace k2_client
{
template <class ContainerAllocator>
struct Activities_ {
  typedef Activities_<ContainerAllocator> Type;

  Activities_()
  : eyeLeftClosed(false)
  , eyeRightClosed(false)
  , mouthOpen(false)
  , mouthMoved(false)
  , lookingAway(false)
  {
  }

  Activities_(const ContainerAllocator& _alloc)
  : eyeLeftClosed(false)
  , eyeRightClosed(false)
  , mouthOpen(false)
  , mouthMoved(false)
  , lookingAway(false)
  {
  }

  typedef uint8_t _eyeLeftClosed_type;
  uint8_t eyeLeftClosed;

  typedef uint8_t _eyeRightClosed_type;
  uint8_t eyeRightClosed;

  typedef uint8_t _mouthOpen_type;
  uint8_t mouthOpen;

  typedef uint8_t _mouthMoved_type;
  uint8_t mouthMoved;

  typedef uint8_t _lookingAway_type;
  uint8_t lookingAway;


  typedef boost::shared_ptr< ::k2_client::Activities_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::k2_client::Activities_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Activities
typedef  ::k2_client::Activities_<std::allocator<void> > Activities;

typedef boost::shared_ptr< ::k2_client::Activities> ActivitiesPtr;
typedef boost::shared_ptr< ::k2_client::Activities const> ActivitiesConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::k2_client::Activities_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::k2_client::Activities_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace k2_client

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::k2_client::Activities_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::k2_client::Activities_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::k2_client::Activities_<ContainerAllocator> > {
  static const char* value() 
  {
    return "92fd995748ea10952cb2ee4d39fc8c66";
  }

  static const char* value(const  ::k2_client::Activities_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x92fd995748ea1095ULL;
  static const uint64_t static_value2 = 0x2cb2ee4d39fc8c66ULL;
};

template<class ContainerAllocator>
struct DataType< ::k2_client::Activities_<ContainerAllocator> > {
  static const char* value() 
  {
    return "k2_client/Activities";
  }

  static const char* value(const  ::k2_client::Activities_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::k2_client::Activities_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool eyeLeftClosed\n\
bool eyeRightClosed\n\
bool mouthOpen\n\
bool mouthMoved\n\
bool lookingAway\n\
";
  }

  static const char* value(const  ::k2_client::Activities_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::k2_client::Activities_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::k2_client::Activities_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.eyeLeftClosed);
    stream.next(m.eyeRightClosed);
    stream.next(m.mouthOpen);
    stream.next(m.mouthMoved);
    stream.next(m.lookingAway);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Activities_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::k2_client::Activities_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::k2_client::Activities_<ContainerAllocator> & v) 
  {
    s << indent << "eyeLeftClosed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.eyeLeftClosed);
    s << indent << "eyeRightClosed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.eyeRightClosed);
    s << indent << "mouthOpen: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mouthOpen);
    s << indent << "mouthMoved: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mouthMoved);
    s << indent << "lookingAway: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lookingAway);
  }
};


} // namespace message_operations
} // namespace ros

#endif // K2_CLIENT_MESSAGE_ACTIVITIES_H

