/* Auto-generated by genmsg_cpp for file /home/prdemo/ros/local/k2_client/msg/Appearance.msg */
#ifndef K2_CLIENT_MESSAGE_APPEARANCE_H
#define K2_CLIENT_MESSAGE_APPEARANCE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace k2_client
{
template <class ContainerAllocator>
struct Appearance_ {
  typedef Appearance_<ContainerAllocator> Type;

  Appearance_()
  : wearingGlasses(false)
  {
  }

  Appearance_(const ContainerAllocator& _alloc)
  : wearingGlasses(false)
  {
  }

  typedef uint8_t _wearingGlasses_type;
  uint8_t wearingGlasses;


  typedef boost::shared_ptr< ::k2_client::Appearance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::k2_client::Appearance_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Appearance
typedef  ::k2_client::Appearance_<std::allocator<void> > Appearance;

typedef boost::shared_ptr< ::k2_client::Appearance> AppearancePtr;
typedef boost::shared_ptr< ::k2_client::Appearance const> AppearanceConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::k2_client::Appearance_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::k2_client::Appearance_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace k2_client

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::k2_client::Appearance_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::k2_client::Appearance_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::k2_client::Appearance_<ContainerAllocator> > {
  static const char* value() 
  {
    return "69bdacaca29a46fe02e2540c6fec5a99";
  }

  static const char* value(const  ::k2_client::Appearance_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x69bdacaca29a46feULL;
  static const uint64_t static_value2 = 0x02e2540c6fec5a99ULL;
};

template<class ContainerAllocator>
struct DataType< ::k2_client::Appearance_<ContainerAllocator> > {
  static const char* value() 
  {
    return "k2_client/Appearance";
  }

  static const char* value(const  ::k2_client::Appearance_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::k2_client::Appearance_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool wearingGlasses\n\
";
  }

  static const char* value(const  ::k2_client::Appearance_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::k2_client::Appearance_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::k2_client::Appearance_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.wearingGlasses);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Appearance_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::k2_client::Appearance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::k2_client::Appearance_<ContainerAllocator> & v) 
  {
    s << indent << "wearingGlasses: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wearingGlasses);
  }
};


} // namespace message_operations
} // namespace ros

#endif // K2_CLIENT_MESSAGE_APPEARANCE_H

