/* Auto-generated by genmsg_cpp for file /home/prdemo/ros/local/k2_client/msg/JointOrientationAndType.msg */
#ifndef K2_CLIENT_MESSAGE_JOINTORIENTATIONANDTYPE_H
#define K2_CLIENT_MESSAGE_JOINTORIENTATIONANDTYPE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/Quaternion.h"

namespace k2_client
{
template <class ContainerAllocator>
struct JointOrientationAndType_ {
  typedef JointOrientationAndType_<ContainerAllocator> Type;

  JointOrientationAndType_()
  : orientation()
  , jointType(0)
  {
  }

  JointOrientationAndType_(const ContainerAllocator& _alloc)
  : orientation(_alloc)
  , jointType(0)
  {
  }

  typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _orientation_type;
   ::geometry_msgs::Quaternion_<ContainerAllocator>  orientation;

  typedef int32_t _jointType_type;
  int32_t jointType;


  typedef boost::shared_ptr< ::k2_client::JointOrientationAndType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::k2_client::JointOrientationAndType_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct JointOrientationAndType
typedef  ::k2_client::JointOrientationAndType_<std::allocator<void> > JointOrientationAndType;

typedef boost::shared_ptr< ::k2_client::JointOrientationAndType> JointOrientationAndTypePtr;
typedef boost::shared_ptr< ::k2_client::JointOrientationAndType const> JointOrientationAndTypeConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::k2_client::JointOrientationAndType_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::k2_client::JointOrientationAndType_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace k2_client

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::k2_client::JointOrientationAndType_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::k2_client::JointOrientationAndType_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::k2_client::JointOrientationAndType_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7cc8c53731606896e746bc308db6a603";
  }

  static const char* value(const  ::k2_client::JointOrientationAndType_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7cc8c53731606896ULL;
  static const uint64_t static_value2 = 0xe746bc308db6a603ULL;
};

template<class ContainerAllocator>
struct DataType< ::k2_client::JointOrientationAndType_<ContainerAllocator> > {
  static const char* value() 
  {
    return "k2_client/JointOrientationAndType";
  }

  static const char* value(const  ::k2_client::JointOrientationAndType_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::k2_client::JointOrientationAndType_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/Quaternion orientation\n\
int32 jointType\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::k2_client::JointOrientationAndType_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::k2_client::JointOrientationAndType_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::k2_client::JointOrientationAndType_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.orientation);
    stream.next(m.jointType);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct JointOrientationAndType_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::k2_client::JointOrientationAndType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::k2_client::JointOrientationAndType_<ContainerAllocator> & v) 
  {
    s << indent << "orientation: ";
s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "jointType: ";
    Printer<int32_t>::stream(s, indent + "  ", v.jointType);
  }
};


} // namespace message_operations
} // namespace ros

#endif // K2_CLIENT_MESSAGE_JOINTORIENTATIONANDTYPE_H

