/* Auto-generated by genmsg_cpp for file /home/prdemo/ros/local/k2_client/msg/Lean.msg */
#ifndef K2_CLIENT_MESSAGE_LEAN_H
#define K2_CLIENT_MESSAGE_LEAN_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace k2_client
{
template <class ContainerAllocator>
struct Lean_ {
  typedef Lean_<ContainerAllocator> Type;

  Lean_()
  : leanX(0.0)
  , leanY(0.0)
  {
  }

  Lean_(const ContainerAllocator& _alloc)
  : leanX(0.0)
  , leanY(0.0)
  {
  }

  typedef double _leanX_type;
  double leanX;

  typedef double _leanY_type;
  double leanY;


  typedef boost::shared_ptr< ::k2_client::Lean_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::k2_client::Lean_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Lean
typedef  ::k2_client::Lean_<std::allocator<void> > Lean;

typedef boost::shared_ptr< ::k2_client::Lean> LeanPtr;
typedef boost::shared_ptr< ::k2_client::Lean const> LeanConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::k2_client::Lean_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::k2_client::Lean_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace k2_client

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::k2_client::Lean_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::k2_client::Lean_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::k2_client::Lean_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c40366f6936def86f552f4754f13c41b";
  }

  static const char* value(const  ::k2_client::Lean_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc40366f6936def86ULL;
  static const uint64_t static_value2 = 0xf552f4754f13c41bULL;
};

template<class ContainerAllocator>
struct DataType< ::k2_client::Lean_<ContainerAllocator> > {
  static const char* value() 
  {
    return "k2_client/Lean";
  }

  static const char* value(const  ::k2_client::Lean_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::k2_client::Lean_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 leanX\n\
float64 leanY\n\
";
  }

  static const char* value(const  ::k2_client::Lean_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::k2_client::Lean_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::k2_client::Lean_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.leanX);
    stream.next(m.leanY);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Lean_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::k2_client::Lean_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::k2_client::Lean_<ContainerAllocator> & v) 
  {
    s << indent << "leanX: ";
    Printer<double>::stream(s, indent + "  ", v.leanX);
    s << indent << "leanY: ";
    Printer<double>::stream(s, indent + "  ", v.leanY);
  }
};


} // namespace message_operations
} // namespace ros

#endif // K2_CLIENT_MESSAGE_LEAN_H

