(cl:in-package k2_client-msg)
(cl:export '(HEADER-VAL
          HEADER
          BEAMANGLE-VAL
          BEAMANGLE
          BEAMANGLECONFIDENCE-VAL
          BEAMANGLECONFIDENCE
          AUDIOSTREAM-VAL
          AUDIOSTREAM
          NUMBYTESPERSAMPLE-VAL
          NUMBYTESPERSAMPLE
          NUMSAMPLESPERFRAME-VAL
          NUMSAMPLESPERFRAME
          FRAMELIFETIME-VAL
          FRAMELIFETIME
          SAMPLINGFREQUENCY-VAL
          SAMPLINGFREQUENCY
))